# -*- mode: ruby -*-

$script = <<EOT
apt-get update -y
apt-get install -y gdb make
EOT

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision "shell", inline: $script
end
